CREATE DATABASE chirpy;
USE chirpy;

CREATE TABLE `chirps` (
  id BIGINT(10) AUTO_INCREMENT NOT NULL,
  author VARCHAR(45) NOT NULL,
  chirp VARCHAR(400) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);